* DONE [#C] QUESTION: What is the difference between TI linker script and GCC linker script?
  DEADLINE: <2026-07-31 Fri> CLOSED: [2026-07-29 Wed 23:07]
  - Note taken on [2026-07-30 Thu 09:44] \\
    If we don't set it explicitly, the CPU wouldn't be able to write to EALLOW protected registers. We must set it explicitly.
  - Note taken on [2026-07-29 Wed 12:34] \\
    This is to prevent spurious CPU writes. But it enables by default (it's set to 0). Do we need to explicitly disable it?
  [2026-07-29 Wed]
* DONE Test canopennode C2000 bootloader on Launchpad dev board [1/2]
  DEADLINE: <2026-07-31 Fri> CLOSED: [2026-08-04 Tue 18:23]
  - Note taken on [2026-08-04 Tue 18:23] \\
    This project won't work for the same reason that we have figured out since day one. The original project is intended to be flashed into FLASH memory then loaded into RAM. Its backdoor is nothing more than a waiting windows that looks for valid SDO write to enter bootloader.
- [X] Modify code to work with F28069M
- [ ] Load code into dev board
  [2026-07-31 Fri]
* TODO Finish Fiverr starter process
  DEADLINE: <2026-08-06 Thu>
  [2026-08-04 Tue]
* TODO Implement a fully functional RISC-V microcontroller [0/6]
  - [ ] Define specifications.
  - Functional design.
    - [ ] Implement ALU.
    - [ ] Stimulation and verification.
  - Synthesis design.
    - [ ] Stimulation and verification.
  - Technology mapping.
    - [ ] Stimulation and verification.
  - Place and route.
    - [ ] Stimulation and verification.
  - [ ] Final verification against specifications.
  [2026-08-06 Thu]
* TODO Implement Single Cycle RISC-V CPU
  DEADLINE: <2026-08-09 Sun>
- Implement ALU
  - [ ] Carry Look Ahead Adder
  [2026-08-07 Fri]
